allow-flight=true
difficulty=peaceful
enable-command-block=false
enable-query=false
enable-rcon=false
generate-structures=true
level-name=worldgen-smoke
level-seed=6840335614481275123
level-type=minecraft:normal
max-players=1
max-tick-time=180000
motd=Megalophobia worldgen smoke test
online-mode=false
server-port=0
simulation-distance=2
spawn-protection=0
sync-chunk-writes=false
view-distance=2
